"""
NVIDIA/SkillSpector — Agno Knowledge Skill
Generated by GitScape.ai · https://gitscape.ai
AgentSkills standard: https://agentskills.io

Usage:
    from agno.agent import Agent
    from nvidia_skillspector_agno_skill import NvidiaSkillspectorKnowledge

    agent = Agent(
        name="nvidia-skillspector-agent",
        knowledge=NvidiaSkillspectorKnowledge,
        search_knowledge=True,
    )
    agent.knowledge.load()
"""
from pathlib import Path

from agno.knowledge.text import TextKnowledgeBase
from agno.vectordb.lancedb import LanceDb, SearchType

# Index SKILL.md + every references/*.md (progressive-disclosure package).
_SKILL_DIR = Path(__file__).parent

NvidiaSkillspectorKnowledge = TextKnowledgeBase(
    path=str(_SKILL_DIR),
    formats=[".md"],
    vector_db=LanceDb(
        table_name="nvidia_skillspector_skill",
        uri=str(_SKILL_DIR / ".lancedb"),
        search_type=SearchType.hybrid,
    ),
)

__all__ = ["NvidiaSkillspectorKnowledge"]