"""
NVIDIA/SkillSpector — Google ADK Skill
Generated by GitScape.ai · https://gitscape.ai
AgentSkills standard: https://agentskills.io

Usage:
    from google.adk.agents import Agent
    from nvidia_skillspector_adk_skill import NvidiaSkillspectorSkill

    root_agent = Agent(
        name="nvidia-skillspector-agent",
        model="gemini-2.0-flash",
        instruction="Use the NVIDIA/SkillSpector skill to answer codebase questions.",
        tools=[NvidiaSkillspectorSkill],
    )
"""
from pathlib import Path

from google.adk.tools import FunctionTool

_SKILL_DIR = Path(__file__).parent
_SKILL_MD = (_SKILL_DIR / "SKILL.md").read_text(encoding="utf-8")
_REF_DIR = _SKILL_DIR / "references"


def _load_references() -> str:
    if not _REF_DIR.is_dir():
        return ""
    parts = []
    for ref in sorted(_REF_DIR.glob("*.md")):
        parts.append(f"\n\n## {ref.name}\n\n" + ref.read_text(encoding="utf-8"))
    return "".join(parts)


def query_nvidia_skillspector_codebase(question: str) -> str:
    """
    Query the NVIDIA/SkillSpector codebase skill.

    Use when the user asks about the NVIDIA/SkillSpector repository: architecture,
    public API, implementation, configuration, setup, or how to extend it.

    Args:
        question: The specific question about the NVIDIA/SkillSpector codebase.

    Returns:
        Guidance grounded in SKILL.md and its references/.
    """
    context = _SKILL_MD + _load_references()
    return (
        f"[NVIDIA/SkillSpector Skill] {question}\n\n"
        f"Answer using the following skill knowledge:\n{context}"
    )


NvidiaSkillspectorSkill = FunctionTool(func=query_nvidia_skillspector_codebase)

__all__ = ["NvidiaSkillspectorSkill"]