"""
addyosmani/agent-skills — Agno Knowledge Skill
Generated by GitScape.ai · https://gitscape.ai
AgentSkills standard: https://agentskills.io

Usage:
    from agno.agent import Agent
    from addyosmani_agent_skills_agno_skill import AddyosmaniAgentSkillsKnowledge

    agent = Agent(
        name="addyosmani-agent-skills-agent",
        knowledge=AddyosmaniAgentSkillsKnowledge,
        search_knowledge=True,
    )
    agent.knowledge.load()
"""
from pathlib import Path

from agno.knowledge.text import TextKnowledgeBase
from agno.vectordb.lancedb import LanceDb, SearchType

# Index SKILL.md + every references/*.md (progressive-disclosure package).
_SKILL_DIR = Path(__file__).parent

AddyosmaniAgentSkillsKnowledge = TextKnowledgeBase(
    path=str(_SKILL_DIR),
    formats=[".md"],
    vector_db=LanceDb(
        table_name="addyosmani_agent_skills_skill",
        uri=str(_SKILL_DIR / ".lancedb"),
        search_type=SearchType.hybrid,
    ),
)

__all__ = ["AddyosmaniAgentSkillsKnowledge"]