"""
addyosmani/agent-skills — Google ADK Skill
Generated by GitScape.ai · https://gitscape.ai
AgentSkills standard: https://agentskills.io

Usage:
    from google.adk.agents import Agent
    from addyosmani_agent_skills_adk_skill import AddyosmaniAgentSkillsSkill

    root_agent = Agent(
        name="addyosmani-agent-skills-agent",
        model="gemini-2.0-flash",
        instruction="Use the addyosmani/agent-skills skill to answer codebase questions.",
        tools=[AddyosmaniAgentSkillsSkill],
    )
"""
from pathlib import Path

from google.adk.tools import FunctionTool

_SKILL_DIR = Path(__file__).parent
_SKILL_MD = (_SKILL_DIR / "SKILL.md").read_text(encoding="utf-8")
_REF_DIR = _SKILL_DIR / "references"


def _load_references() -> str:
    if not _REF_DIR.is_dir():
        return ""
    parts = []
    for ref in sorted(_REF_DIR.glob("*.md")):
        parts.append(f"\n\n## {ref.name}\n\n" + ref.read_text(encoding="utf-8"))
    return "".join(parts)


def query_addyosmani_agent_skills_codebase(question: str) -> str:
    """
    Query the addyosmani/agent-skills codebase skill.

    Use when the user asks about the addyosmani/agent-skills repository: architecture,
    public API, implementation, configuration, setup, or how to extend it.

    Args:
        question: The specific question about the addyosmani/agent-skills codebase.

    Returns:
        Guidance grounded in SKILL.md and its references/.
    """
    context = _SKILL_MD + _load_references()
    return (
        f"[addyosmani/agent-skills Skill] {question}\n\n"
        f"Answer using the following skill knowledge:\n{context}"
    )


AddyosmaniAgentSkillsSkill = FunctionTool(func=query_addyosmani_agent_skills_codebase)

__all__ = ["AddyosmaniAgentSkillsSkill"]