"""
Framework exporters on the new package shape.

Carries over the ADK / Agno wrappers but points them at SKILL.md + references/
(the progressive-disclosure package) instead of bundling the whole DIGEST.md as a
RAG blob.

Author: GitScape.ai
"""
from __future__ import annotations

from jinja2 import BaseLoader, Environment

_env = Environment(loader=BaseLoader(), autoescape=False)


def _to_class_name(owner: str, repo: str) -> str:
    """'my-repo' -> 'MyRepo' (PascalCase)."""
    combined = f"{owner}_{repo}"
    return "".join(word.capitalize() for word in combined.replace("-", "_").split("_"))


def _to_module_name(owner: str, repo: str) -> str:
    """snake_case module name."""
    return f"{owner}_{repo}".lower().replace("-", "_")


def _to_skill_name(owner: str, repo: str) -> str:
    return f"{owner.lower()}-{repo.lower()}"

ADK_TEMPLATE = '''\
"""
{{ display_name }} — Google ADK Skill
Generated by GitScape.ai · https://gitscape.ai
AgentSkills standard: https://agentskills.io

Usage:
    from google.adk.agents import Agent
    from {{ module_name }}_adk_skill import {{ class_name }}Skill

    root_agent = Agent(
        name="{{ skill_name }}-agent",
        model="gemini-2.0-flash",
        instruction="Use the {{ display_name }} skill to answer codebase questions.",
        tools=[{{ class_name }}Skill],
    )
"""
from pathlib import Path

from google.adk.tools import FunctionTool

_SKILL_DIR = Path(__file__).parent
_SKILL_MD = (_SKILL_DIR / "SKILL.md").read_text(encoding="utf-8")
_REF_DIR = _SKILL_DIR / "references"


def _load_references() -> str:
    if not _REF_DIR.is_dir():
        return ""
    parts = []
    for ref in sorted(_REF_DIR.glob("*.md")):
        parts.append(f"\\n\\n## {ref.name}\\n\\n" + ref.read_text(encoding="utf-8"))
    return "".join(parts)


def query_{{ module_name }}_codebase(question: str) -> str:
    """
    Query the {{ display_name }} codebase skill.

    Use when the user asks about the {{ display_name }} repository: architecture,
    public API, implementation, configuration, setup, or how to extend it.

    Args:
        question: The specific question about the {{ display_name }} codebase.

    Returns:
        Guidance grounded in SKILL.md and its references/.
    """
    context = _SKILL_MD + _load_references()
    return (
        f"[{{ display_name }} Skill] {question}\\n\\n"
        f"Answer using the following skill knowledge:\\n{context}"
    )


{{ class_name }}Skill = FunctionTool(func=query_{{ module_name }}_codebase)

__all__ = ["{{ class_name }}Skill"]
'''

AGNO_TEMPLATE = '''\
"""
{{ display_name }} — Agno Knowledge Skill
Generated by GitScape.ai · https://gitscape.ai
AgentSkills standard: https://agentskills.io

Usage:
    from agno.agent import Agent
    from {{ module_name }}_agno_skill import {{ class_name }}Knowledge

    agent = Agent(
        name="{{ skill_name }}-agent",
        knowledge={{ class_name }}Knowledge,
        search_knowledge=True,
    )
    agent.knowledge.load()
"""
from pathlib import Path

from agno.knowledge.text import TextKnowledgeBase
from agno.vectordb.lancedb import LanceDb, SearchType

# Index SKILL.md + every references/*.md (progressive-disclosure package).
_SKILL_DIR = Path(__file__).parent

{{ class_name }}Knowledge = TextKnowledgeBase(
    path=str(_SKILL_DIR),
    formats=[".md"],
    vector_db=LanceDb(
        table_name="{{ module_name }}_skill",
        uri=str(_SKILL_DIR / ".lancedb"),
        search_type=SearchType.hybrid,
    ),
)

__all__ = ["{{ class_name }}Knowledge"]
'''

_TEMPLATES = {"adk": ADK_TEMPLATE, "agno": AGNO_TEMPLATE}


def render_framework_export(framework: str, owner: str, repo: str) -> str:
    framework = framework.lower()
    if framework not in _TEMPLATES:
        raise ValueError(f"Unsupported framework '{framework}'. Supported: {list(_TEMPLATES)}")
    context = {
        "display_name": f"{owner}/{repo}",
        "class_name": _to_class_name(owner, repo),
        "module_name": _to_module_name(owner, repo),
        "skill_name": _to_skill_name(owner, repo),
    }
    return _env.from_string(_TEMPLATES[framework]).render(**context)


def render_exporters(owner: str, repo: str) -> dict[str, str]:
    """All exporter files, keyed by their path within the skill package."""
    module = _to_module_name(owner, repo)
    return {
        f"exporters/{module}_adk_skill.py": render_framework_export("adk", owner, repo),
        f"exporters/{module}_agno_skill.py": render_framework_export("agno", owner, repo),
    }
